config/routes.rb
Rails.application.routes.draw do

  resources :posts do
    member do
      patch "upvote", to: "posts#upvote"
    end
    # post 'comments', to: 'comments#create'
    resources :comments, only: [:create, :destroy]
  end

  devise_for :users , post: 'users'

  get 'welcome/index'
  root 'welcome#index'

  get '/story', to: 'welcome#story'

  resource :friendships, only: [:create , :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :body, presence: true, allow_blank: false
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :follower, class_name:"User"
  belongs_to :followed, class_name:"User"

  validates :follower_id , presence: true
  validates :followed_id , presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many_attached :images
  validates :body, presence: true
  validate :image_type
  has_many :comments, dependent: :destroy

  acts_as_votable

  def thumbnail input
    return self.images[input].variant(resize: '300x300!').processed
  end

  private
  def image_type
    if images.attached? == false
      errors.add(:image, "is missing")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  acts_as_voter

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :avatar
  after_commit :add_default_avatar, on: %i[create update]

  has_many :active_friendships, class_name:"Friendship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_friendships, class_name:"Friendship", foreign_key: "follower_id", dependent: :destroy
  has_many :following, through: :active_friendships, source: :followed
  has_many :followers, through: :passive_friendships, source: :follower

  def follow user
    active_friendships.create(followed_id: user.id)
  end

  def unfollow user
    active_friendships.find_by(followed_id: user.id).destroy
  end

  def following? user
    following.include?(user)
  end

  def avatar_thumbnail
    if avatar.attached?
      avatar.variant(resize: "100x100!").processed
    else
      '/default_profile.jpg'
    end
  end

  private
  def add_default_avatar
    unless avatar.attached?
      avatar.attach(
        io: File.open(
          Rails.root.join(
            'app','assets','images','default_profile.jpg'
          )
        ),
        filename: 'default_profile.jpg',
        content_type: 'image/jpg'
        )
      end
    end
  private
  def username
    return email.split('@')[0].capitalize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session

  before_action :configure_permitted_parameters,
                if: :devise_controller?;


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  before_action :authenticate_user!

  def create
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user
    @comment.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @post = Post.find params[:post_id]
    @comment = @post.comments.find params[:id]
    @comment.destroy
    redirect_to post_path(@post)
  end

  private
  def comment_params
    params.require(:comment).permit(:body, :post_id)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_user

  def create
    current_user.follow(@user)
    redirect_back fallback_location: root_path
  end

  def destroy
    current_user.unfollow(@user)
    redirect_back fallback_location: root_path
  end

  private
  def find_user
    @user= User.find(params[:user_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  # before_action :authenticate_user!

  respond_to :js, :html, :json

  def search
    check= User.where("email like ?","%#{params[:search]}%").pluck(:email)
    @user = User.find_by_email(check[0])
    @posts = Post.where(user_id: @user)
  end

  def upvote
    @post = Post.find(params[:id])
    if current_user.voted_up_on? @post
      @post.unvote_by current_user
    else
      @post.upvote_by current_user
    end
    render "vote.js.erb"
  end

  # GET /posts or /posts.json
  def index
    @posts = current_user.posts
    # @user = User.find_by_email(params[:search])
    # @posts = Post.where(user_id: @user)

  end

  # GET /posts/1 or /posts/1.json
  def show
    # @post = Post.all
    @comment = Comment.new
    @comments = @post.comments.order("created_at DESC")
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create

    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }

    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])

    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:body , :user_id ,images: [])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if not user_signed_in?
      redirect_to user_session_path
    else
      @post = current_user.posts.order("created_at DESC")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/create.html.erb
$('#comment_pane').prepend("<%= j render @comment %>");
$('#comment_body').val('');

app/views/layouts/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram Clone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <style>
    @import url('https://fonts.googleapis.com/css2?family=Style+Script&display=swap');
  </style>
  </head>
<body class="<%= controller_name %> <%= action_name %>">

  <%= render 'welcome/header'%>
    <% if notice %>
      <%= render 'layouts/alert'%>
    <%end%>
    <%= yield %>

    <script src="https://code.jquery.com/jquery.js"></script>
    <%# <script src="js/bootstrap.min.js"></script> %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
   <%= form.file_field :images, multiple: :true , class:"form-control" %>
  </div>
  <br>

  <div class="field">
    <%= form.text_field  :body , class:"form-control", placeholder: "Caption" %>
  </div>
  <br>

  <div class="field">
    <%= form.number_field :user_id, id: :post_user_id, type: :hidden,value: current_user.id %>
  </div>

  <div class="actions">
    <%= form.submit "Upload" ,class: "btn btn-primary form-control"%>
  </div>
<% end %>

app/views/posts/_upvote_link.html.erb
<%= content_tag "div", id: "upvote-#{post.id}" do %>
  <%= link_to upvote_post_path(post), method: :patch, remote: true do %>
    <% if current_user.voted_up_on? post%>
    <p class="btn btn-dark">Unlike</p>
    <%else%>
    <p class="btn btn-dark">Like</p>
    <%end%>
  <%end%>
<%end%>

app/views/posts/_votes_score.html.erb
<%= content_tag "div", id: "votes-score-#{post.id}" do %>
  <%= post.cached_votes_score %>
<%end%>

app/views/posts/edit.html.erb
<br>
<div class= "container">
<h1>Editing Post</h1>

<%= render 'form', post: @post %>
<br>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

</div>

app/views/posts/index.html.erb
<h1>All post</h1>
<table>
  <tr>
    <th>Title</th>
    <th>vote</th>
    <th>count</th>
    <th></th>
  </tr>

  <% @posts.each do |article| %>
    <tr>
      <td><%= article.body %></td>
      <td><%= render "posts/upvote_link", post: article%></td>
      <td><%= render "posts/votes_score", post: article %></td>
      <td><%= link_to 'Show', article %></td>
      <td><%= link_to 'Edit', edit_post_path(article) %></td>
      <td><%= link_to 'Delete', article ,
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/posts/new.html.erb
<br><br>
<div class= "container">
<h1>Add New Post</h1>
<br>

<%= render 'form', post: @post %>

<%# <%= link_to 'Back', posts_path %>

</div>

app/views/posts/search.html.erb
<br>
<% if @user == nil %>
  <h1>No Record Found</h1>
<%else%>
<div class="container d-flex flex-row">
  <div>
  <%= image_tag(@user.avatar_thumbnail, class:"xyz")%>
  </div>
  <div class="user_info ">
  <% if user_signed_in? && current_user != @user%>
    <strong><%= @user.email.split('@')[0].capitalize%></strong>
    <br/>
    <%if current_user.following?(@user) %>
      <%= button_to "Unfollow", friendships_path(user_id: @user.id), method: :delete, class:"btn btn-light"%>
    <%else%>
      <%= button_to "Follow", friendships_path(user_id: @user.id),class: "btn btn-primary"%>
    <%end%>
  <%end%>
  </div>
</div>
<%end %>
<br>
<br>

<%if current_user.following?(@user) %>
<div class="container friendpost">
<% @posts.each do |post| %>
<div class="card fpost">
  <%= image_tag(post.thumbnail(0) ,class: "img-thumbnail center" )%>
  <div class="card-body">
    <p class="card-text"><%= post.body %></p>

    <div class="d-flex flex-row">
      <%= render "posts/votes_score", post: post %>
      <i class="fa fa-heart" style="font-size:28px;color:red; margin-left: 2%"></i>
    </div>
    <br>
    <div class="d-flex flex-row">
      <%= render "posts/upvote_link", post: post ,class:"btn btn-dark"%>
      <p><%= link_to 'Show', post ,class:"btn btn-dark b1" %></p>
    </div>
   </div>
  </div>
<% end%>
</div>
<%end%>

app/views/posts/show.html.erb
<% (0...@post.images.count).each do |image|%>
  <%= image_tag(@post.thumbnail(image))%>
<% end%>

<p>
  <strong>Caption:</strong>
  <%= @post.body %>
</p>


<%= link_to 'Back', root_path %>
<% if current_user == @post.user%>
  <%= link_to 'Edit', edit_post_path(@post) %> |
  <%= link_to 'Delete', post_path ,
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
<%end%>
<br>
<br>

<%= form_with model: [@post, @comment],local: true do |f| %>
<%= f.text_field :body %>
<%= f.submit "Comment" %>
<%end%>
<br>


<% @comments.each do |comment|%>
  [<%= comment.created_at.strftime("%I:%M:%S")%>]
  <strong><%= comment.user.email.split('@')[0].capitalize%>:</strong>
  <% if current_user && current_user == comment.user || current_user == @post.user%>
    <%= comment.body%>
    <%= link_to "Delete", post_comment_path(@post, comment), method: :delete  , class: "btn btn-danger btn-sm ms-2"%>
  <% end %>
  <hr/>
  <br/>
  <br/>
<%end%>

app/views/posts/vote.js.erb
document.getElementById("upvote-<%= @post.id %>").innerHTML = "<%= j render "posts/upvote_link", post: @post %>";
document.getElementById("votes-score-<%= @post.id %>").innerHTML = "<%= j render "posts/votes_score", post: @post %>";

app/views/welcome/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  <i class="fa fa-instagram ms-5" aria-hidden="true" style="font-size:28px;color:white"></i>
  <%= link_to 'Instagram' , root_path , class:"navbar-brand ms-2"%>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse d-flex flex-row-reverse" id="navbarSupportedContent">
    <ul class="navbar-nav">
    <% if user_signed_in?%>
      <li class="nav-item me-2 pt-2" >
      <%= form_with url: '/search', method: :get, local: true do |f| %>
      <%= f.text_field :q, name: "search", id: :q , placeholder: "email or username"%>
      <%= f.submit "Search" , class:"btn btn-outline-success" %>
      <% end %>
      </li>
      <li class="nav-item me-3 pt-2 ms-0">
          <%= link_to 'Add Post', new_post_path , class: "nav-link btn btn-primary"%>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        <%= image_tag(current_user.avatar_thumbnail, :style => "border-radius:50%; width:40%") %>
        </a>
        <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownMenuButton2">
          <li style= "color:"><a><%= link_to 'Edit Profile', edit_user_registration_path , class: "nav-link dropdown-item"%> </a></li>
          <li><a><%= link_to 'Sign Out', destroy_user_session_path  , method: :delete, class: "nav-link dropdown-item"%></a></li>
        </ul>
      </li>
    <% else %>
      <li class="nav-item">
        <%= link_to 'Sign Up', new_user_registration_path , class: "nav-link"%>
      </li>
    <% end %>
    </ul>
  </div>
</div>
</nav>

app/views/welcome/index.html.erb
<div class="container d-flex">
  <div>
    <%= image_tag(current_user.avatar_thumbnail, class:"xyz")%>
  </div>
  <div class="userinfotable">
  <strong><%= current_user.email.split('@')[0].capitalize%></strong>
    <table class="table">
      <thead>
      <tr>
        <th>Posts</th>
        <th>Followers</th>
        <th>Following</th>
      </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= current_user.posts.all.count%></td>
          <td><%= current_user.followers.all.count %></td>
          <td><%= current_user.following.all.count%></td>
        </tr>
      </tbody>
    </table>
    </div>
</div>

<div class="container mypost">
<% @post.each do |post| %>
<div class="card">
  <%= image_tag(post.thumbnail(0) , class: "img-thumbnail center")%>
  <div class="card-body">
    <p class="card-text"><strong>Caption: </strong><%=  post.body %></p>
    <div class="d-flex flex-row">
    <%= render "posts/votes_score", post: post %>
    <i class="fa fa-heart" style="font-size:28px;color:red; margin-left: 2%"></i>
    </div>
    <br>
    <div class="d-flex flex-row">
    <%= render "posts/upvote_link", post: post ,class:"btn btn-dark"%>
    <p><%= link_to 'Show', post ,class:"btn btn-dark b1" %></p>
    </div>
  </div>
</div>
<% end%>
</div>